/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 ./public/models/south_korea.glb
Author: Space XR Academy (https://sketchfab.com/SpaceXRAcademy)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/south-korea-cd7bd66fe1fd48cd967f7e712c895245
Title: South Korea
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Taegukgi (props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/south_korea.glb')
  const { actions } = useAnimations(animations, group)

  return (
    <group ref={group} {...props} dispose={null} position={[0,7,-12]} scale={[3,3,3]}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Sketchfab_model_0" rotation={[-Math.PI / 2, 0, 0]}>
                <group name="root_1">
                  <group name="GLTF_SceneRootNode_2" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="RootNode_(gltf_orientation_matrix)_0_3" rotation={[-Math.PI / 2, 0, 0]}>
                      <group name="RootNode_(model_correction_matrix)_1_4">
                        <group name="root_2_5">
                          <group name="GLTF_SceneRootNode_3_6" rotation={[Math.PI / 2, 0, 0]}>
                            <group name="Flag_ShapeKeys_2_4_7">
                              <group name="mesh_0_5_8">
                                <group name="mesh_0_9">
                                  <mesh name="mesh_0" geometry={nodes.mesh_0.geometry} material={materials.Flag} morphTargetDictionary={nodes.mesh_0.morphTargetDictionary} morphTargetInfluences={nodes.mesh_0.morphTargetInfluences} />
                                </group>
                              </group>
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/south_korea.glb')
